language: nix
sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode8.2

env:
- NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/09c7601c204016c8ecdefd474f721fb841e834df.tar.gz

install:
# Install Stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64 | tar
  xz --strip-components=1 -C ~/.local/bin
# TODO: install bridge
# TODO: print build of cardano-sl
- nix-shell --run "npm install"

script:   
- export DAEDALUS_VERSION=$TRAVIS_BUILD_NUMBER
# Fix https://github.com/NixOS/nixpkgs/issues/23605
- export SSL_CERT_FILE=$NIX_SSL_CERT_FILE 
- nix-shell --run "npm run package -- --icon installers/icons/256x256"
- du -sh release
- pushd installers
# TODO: copy cardano-node
- stack --no-terminal --nix build --exec make-installer --jobs 4
- mkdir -p dist

notifications:
  slack:
    secure: hfzreJ033RxFI2UYtcGJ+MFgQX08UyUnQwhb8X8CuVuIZXDWhxz9JLMEUuL6QqogtffbiqfqIhyDwZ0PsE3aEJaHQAQ7lxJkMjZFU/o+CYvHBQy+WYCa/sFM0C8cEXn3Wb/LmhjvtKAgF302tnD5PAPglZTGtCJHpihKG/Wc+YwF2aFSon0DqoMtVmwVPvhD/WlAHyszARsE9C7jH7jN43gwupAmwj7QLH+kd96HKrrc2ItgMS0f5ucFnpM900c9LwhE5StxVdgTXLnogWQKcd1f4DwTNoXfS3Dy6VJkKj049VScvavcFcVPBL9xU62SMMy/eS/yRcHZkxJehUi16aoir2GXNZOKjQVQ85zEQofQgkR+b4roJJmtWJuCoyE0nptoHgDi4BlLwFuC1g7pkngtLvo3BrG3IjhV+s7QuhxFA9aA8MBQDTRBQNeZdU2I/iwJaYsggGQ2JYA/B2AE4C0sentbegGumsY4fah6HVQGOOZoCl3k9fmMDS42/D55kdteRAQBZBlixLHMXTsMf90jcJJGi/vkzVEnhby63RdTRNDW6MBA6RgvUIpI0VQgAIEM8LFHMNeHMYLoj++NnSI3gCrX8zi8nrnCUJmpCQ89WLDRbVy3rFltgcd7ds8SlRxMtSXCO9lulq/Q6Gk65mRhuq/My0FqBbT+DQUBg04=

deploy:
  provider: s3
  access_key_id: AKIAJKSJR3FUN3CWKC5Q
  secret_access_key:
    secure: PtDmmCXYtnIvoR2j17TJNqdEtAWyeN1JN7x8Ecs47C/77lUxuHIJn/9iqyWYHRqkc0pJvanUHmYQY1dxQTHmIdcZwPaI7i9Hib5xEpi+1AKleZ4fTxiJ9Vt1V7cmCnx9HJ8KEmzbmrD9fPj5N2sl/ROYGWa+gNN89UsX462ms577jSBhdvJcaIeACbyEmnFDct0l5Hv23SF3Ciljiva+OLtSahuuhWjTmjb8kS/KjhU5Sl2uF5ZPsi9Xt7y9w3hvowQn/YCxz+161ekKDQkdWPaIYD0xawo6U5Z/GX3HGUYmZBZvlwEaCDa88dXrEfaxH9eYrRyRSuf93DIDMCdiWAWDf1vZBxYuTH8B88ptgjh9xGYMFdUtLq7sWtoMumYWsW8ldnImI1Y1zNdBXV0LrSmKV5Gy0E1cHYyv+rNCcR5tXBlkVOLRKnVLxA8XGfQjFCTQwaljarx7NKqToHzkOb9uiOvPyBvD6WQTYEeebzop/Uj6rFxOLjJ1Fb7xM6zeLkFktEThReDFefX34a8qzD6YnJuBbVTOvROoBC06I4FaBo5rwrpHe7tLohwxLASdhrCy/e6SMsehEOS+luwHNDEV95TnzcNDITqzKQHPdI1J0OYXEal3MkhYwYEtGuwnNDOEfd1nm+2BSw8L0F+pAyP/GBlnLUO9QVg+LWvKOfw=
  bucket: daedalus-travis
  region: eu-central-1
  local_dir: dist
  skip_cleanup: true
  on:
    all_branches: true
